name: Pride in Business
favicon: null
layout_spectrum: 0.5352053074166179
typography_spectrum: 0.7188383317552507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#303030'
    - '#e7168b'
    - '#ffffff'
    - '#808080'
    - '#ff8080'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.3170394466724247
purpose: []
